### ISSUE TITLE
put release on github as well as the windows store?

### ISSUE THREAD

**Issue by Pomax** [torum/Image-viewer#17]
not everyone can use the windows store, it would be super useful if there was a normal release here on github, too, so folks can just download and immediately run things on older versions of windows, or systems where the windows store has either been locked down, or straight up been removed.

**Comment by torum** [comment]
Thank you for your suggestion. I could upload the install file here as you suggested. But the thing is that install file needs to be digitally sighed (which is costly and troublesome) otherwise you get annoying warnings from Windows when you install it. In the other hand, when released via Microsoft store, the store takes care of digital signature of the installer for free. It notifies the update too. So it is better, safer and convenient to use Microsoft store.

However, if, as you said, not everyone can use Microsoft store, I'll upload the installer here as well. Thank you again for your suggestion!

**Comment by Pomax** [comment]
Probably not though: people who download releases from github know how to say "yes" to "this package isn't signed" =)
