### ISSUE TITLE
Windows 10 - Command line

### ISSUE THREAD

**Issue by RottenRonnie** [torum/Image-viewer#6]
Situation - when running from the command line on Win 10, I expect the command
`imageviewer *`
would open and display all the associated image files from within the current directory, but it simply invokes the application with the "ImageViewer - Open pictures(s)" selection window. 

![2020-10-09 09_23_25-Window](https://user-images.githubusercontent.com/10812745/95583464-8c08ad00-0a12-11eb-8319-586b0ccf53cd.png)

I had assumed that I could use this similar to feh for linux - https://feh.finalrewind.org/

Also these commands bring up a GUI "about" as opposed to command line options and switches. 
imageviewer /?
imageviewer -h
imageviewer --help

**Comment by torum** [comment]
Thank you! I'll fix "-h" and add "imageviewer *" in the next version.

**Comment by torum** [comment]
It turns out that it is not easy for a GUI app (at least Delphi/Lazarus/Pascal) to write to the console which started. It needed to be created as a "console application" to do that. In stead, I decided to create a new console window and write a help there when encounter -h option.

As for the "imageviewer *", it is done (v1.2.13). The behavior is pretty much the same as "imageviewer ./".

**Comment by mp3qwer** [comment]
I miss to command line options:
1 for background color
2 and more important Start InFrame Slideshow

otherwise nice little tool
